## Get complete metadata for a census api dataset

#' Get variable and geography metadata in a single function
#' @param name (character) name of censusapi dataset
#' @param year (numeric) vintage year
#' @export

getCensusInfo <- function(name="acs/acs5", year=2018){
  geo = listCensusMetadata(name = name,
                           type = "geography",
                           vintage = year)
  vars = listCensusMetadata(name = name,
                            type = "variables",
                            vintage = year)
  ddat <- list(geo,vars)
  assign(paste("metadata",name,year,sep="_"), ddat, envir = .GlobalEnv)
  
}


## Get Group-based Metadata view

#' View the available groups for each census api endpoint
#' @param name (character) name of the census api enpoint
#' @param year (numeric) vintage of the dataset
#' @export
getCensusGroups <- function(name="acs/acs5",year=2018){
  metadata = as.data.frame(listCensusMetadata(name=name,vintage=year,type="variables"))
  meta_red = metadata[!duplicated(metadata$group),]
  meta_red2 = meta_red[c("group","concept")]
  assign("census_groups",meta_red2,envir=.GlobalEnv)
}


## Generate longitudal dataset for age by census tract using groups

#' Dataset by census tract for whole US
#' @param start_year (numeric) first year of longitudal data
#' @param end_year (numeric) last year of longitudinal data
#' @param tablename (character) name to assign dataframe generated by function
#' @param group (character) the name of the metadata group
#' @param name (character) the name of the census api dataset
#' @export



concatCensusGroup <- function(name="acs/acs5",start_year=2009,end_year=2018,tablename="age_data",group="B01001",region="tract:*",fipstate=fips){
  years <- seq(from = start_year, to = end_year)
  datlist <- list()
  fipstate
  tracts <- NULL
  pb <- txtProgressBar(start_year, end_year, style=3)
  groupname <- paste("group(",group,")", sep="")
  for(i in years) {
    for (f in fipstate) {
      stateget <- paste("state:", f, sep="")
      iname <- paste("year-",i,f,sep="_")
      dataset <- getCensus(name=name, vintage=i, region = region, regionin = stateget, vars = c(groupname))
      dataset$censusYear <- i
      datlist[[iname]] <- dataset
      
    }
    setTxtProgressBar(pb, i)
  }
  #list2env(datlist,envir=.GlobalEnv) #this splits the list of df's into individual df's
  metadata = listCensusMetadata(name="acs/acs5",vintage=i,type="variables", group = group)
  bound_dataset = dplyr::bind_rows(datlist)
  
  #assign(tablename,bound_dataset,envir=.GlobalEnv)
  #assign(paste(tablename,i,sep="_"),metadata,envir=.GlobalEnv)
  
  
  vars_only = bound_dataset %>% dplyr::select(starts_with(group) & ends_with("E"))
  vars_meta = bound_dataset %>% dplyr::select(!starts_with(group))
  
  metadata = filter(metadata, predicateType == "int" & grepl("E",name))
  metadata = metadata[order(metadata$name),]  
  names(vars_only) = metadata[["label"]]
  vars_only = clean_names(vars_only)
  complete = cbind(vars_meta,vars_only)
  complete[ complete == -666666666 ] <- as.numeric(0)
  complete$censusYear = as.Date(ISOdate(complete$censusYear, 12,31))
  assign(tablename,complete,envir=.GlobalEnv)
}


## Generate longitudal dataset for age by census tract using specified variables

#' Age demographics by census tract for whole US
#' @param start_year (numeric) first year of longitudal data
#' @param end_year (numeric) last year of longitudinal data
#' @param tablename (character) name to assign dataframe generated by function
#' @param name (character) the name of the census api dataset
#' @export

concatCensusVars <- function(name="zbp",start_year=2009,end_year=2018,tablename="zip_code_bp",region="tract:*"){
  years <- seq(from = start_year, to = end_year)
  
  #add array of user inputs here
  prompt <- "enter the variables you want (space-separated list) \n"
  variables <- as.character(strsplit(readline(prompt), " ")[[1]])
  pb <- txtProgressBar(start_year, end_year, style=3)
  
  datlist <- list()
  fips
  tracts <- NULL
  for(i in years) {
    for (f in fips) {
      stateget <- paste("state:", f, sep="")
      iname <- paste("year-",i,f,sep="_")
      dataset <- getCensus(name=name, vintage=i, region = region, regionin = stateget, vars = c(variables))
      dataset$censusYear <- i
      datlist[[iname]] <- dataset
      
    }
    setTxtProgressBar(pb, i)
  }
  #list2env(datlist,envir=.GlobalEnv) #this splits the list of df's into individual df's
  metadata = listCensusMetadata(name=name,vintage=i,type="variables")
  bound_dataset = dplyr::bind_rows(datlist)
  #assign(tablename,bound_dataset,envir=.GlobalEnv)
  #assign(paste(tablename,i,sep="_"),metadata,envir=.GlobalEnv)
  vars_only = bound_dataset[,names(bound_dataset) %in% variables]
  vars_meta = bound_dataset[,!names(bound_dataset) %in% variables]
  metadata = metadata[metadata$name %in% variables,]
  metadata = metadata[order(metadata$name),]  
  names(vars_only) = metadata[["label"]]
  vars_only = clean_names(vars_only)
  complete = cbind(vars_meta,vars_only)
  complete[ complete == -666666666 ] <- as.numeric(0)
  complete$censusYear = as.Date(ISOdate(complete$censusYear, 12,31))
  assign(tablename,complete,envir=.GlobalEnv)
}

